planning_plugin: ompl_interface/OMPLPlanner
request_adapters: >-
  default_planner_request_adapters/ResolveConstraintFrames
  default_planner_request_adapters/FixWorkspaceBounds
  default_planner_request_adapters/FixStartStateBounds
  default_planner_request_adapters/FixStartStateCollision
  default_planner_request_adapters/FixStartStatePathConstraints
  default_planner_request_adapters/AddTimeOptimalParameterization
start_state_max_bounds_error: 0.1
start_state_max_attempts: 300
start_state_max_jiggle_distance: 0.2

planner_configs:
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.0
  KPIECEkConfigDefault:
    type: geometric::KPIECE
    range: 0.0
  BiTRRTkConfigDefault:
    type: geometric::BiTRRT
    range: 0.0
    temp_change_factor: 0.1
    init_temperature: 100
    frountier_threshold: 0.0
    frountier_node_ratio: 0.1
    cost_threshold: 1e300

ur_manipulator:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - KPIECEkConfigDefault
    - RRTConnectkConfigDefault
    - BiTRRTkConfigDefault
  projection_evaluator: joints(elbow_joint, shoulder_lift_joint, shoulder_pan_joint, wrist_1_joint, wrist_2_joint, wrist_3_joint)
  longest_valid_segment_fraction: 0.005
  maximum_waypoint_distance: 0.001
  enforce_constrained_state_space: true

gripper:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - RRTConnectkConfigDefault
