octomap_resolution: 0.01
sensors: []
  # - cupholder_tray_cam_pointcloud
  # - cupholder_tray_cam_depth_image

cupholder_tray_cam_pointcloud:
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  max_range: 5.0
  max_update_rate: 1.0
  padding_offset: 0.1
  padding_scale: 1.0
  point_subsample: 1
  resolution: 0.05
  point_cloud_topic: /wrist_rgbd_depth_sensor/points
  filtered_cloud_topic: /wrist_rgbd_depth_sensor/points

cupholder_tray_cam_depth_image:
  sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  far_clipping_plane_distance: 5.0
  max_update_rate: 1.0
  near_clipping_plane_distance: 0.3
  padding_offset: 0.03
  padding_scale: 4.0
  queue_size: 5
  shadow_threshold: 0.2
  image_topic: /wrist_rgbd_depth_sensor/depth/image_raw
  filtered_cloud_topic: /wrist_rgbd_depth_sensor/points
