octomap_resolution: 0.01
sensors: []
  # - d415_pointcloud
  # - d415_depth_image

d415_pointcloud:
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  max_range: 5.0
  max_update_rate: 1.0
  padding_offset: 0.1
  padding_scale: 1.0
  point_subsample: 1
  resolution: 0.05
  point_cloud_topic: /D415/barista_points
  filtered_cloud_topic: /D415/barista_points_filtered

d415_depth_image:
  sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  far_clipping_plane_distance: 5.0
  max_update_rate: 1.0
  near_clipping_plane_distance: 0.3
  padding_offset: 0.03
  padding_scale: 4.0
  queue_size: 5
  shadow_threshold: 0.2
  image_topic: /D415/aligned_depth_to_color/image_raw
  filtered_cloud_topic: /D415/barista_points_filtered
